### ISSUE TITLE
RULE logStatefulSessionSynchronizationInterceptor.processInvocation.lockAcquired throws cast exception

### ISSUE THREAD

**Issue by RadekKoubsky** [RadekKoubsky/byteman-wildfly-log#1]
When triggered, throws exception:

00:00:58,413 INFO  [stdout](default task-5) cast exception org.jboss.byteman.koubsky.LogHelper_HelperAdapter_Interpreted_94
00:00:58,413 INFO  [stdout](default task-5) java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
00:00:58,414 INFO  [stdout](default task-5)    at org.jboss.byteman.rule.Condition.interpret(Condition.java:116)
00:00:58,414 INFO  [stdout](default task-5)    at org.jboss.byteman.koubsky.LogHelper_HelperAdapter_Interpreted_94.test(ejb.btm)
00:00:58,414 INFO  [stdout](default task-5)    at org.jboss.byteman.koubsky.LogHelper_HelperAdapter_Interpreted_94.execute0(ejb.btm)
00:00:58,414 INFO  [stdout](default task-5)    at org.jboss.byteman.koubsky.LogHelper_HelperAdapter_Interpreted_94.execute(ejb.btm)
00:00:58,415 INFO  [stdout](default task-5)    at org.jboss.byteman.rule.Rule.execute(Rule.java:684)
00:00:58,415 INFO  [stdout](default task-5)    at org.jboss.byteman.rule.Rule.execute(Rule.java:653)
00:00:58,415 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.component.stateful.StatefulSessionSynchronizationInterceptor.processInvocation(StatefulSessionSynchronizationInterceptor.java:87)
00:00:58,415 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,415 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:407)
00:00:58,416 INFO  [stdout](default task-5)    at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:46)
00:00:58,416 INFO  [stdout](default task-5)    at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:83)
00:00:58,416 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,416 INFO  [stdout](default task-5)    at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
00:00:58,417 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,417 INFO  [stdout](default task-5)    at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
00:00:58,417 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,417 INFO  [stdout](default task-5)    at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
00:00:58,418 INFO  [stdout](default task-5)    at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53)
00:00:58,418 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,418 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.component.stateful.StatefulComponentInstanceInterceptor.processInvocation(StatefulComponentInstanceInterceptor.java:66)
00:00:58,418 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,419 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:273)
00:00:58,419 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:340)
00:00:58,419 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:239)
00:00:58,419 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,420 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
00:00:58,420 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,420 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:43)
00:00:58,420 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,420 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:95)
00:00:58,420 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,421 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
00:00:58,421 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,421 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)
00:00:58,421 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,421 INFO  [stdout](default task-5)    at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
00:00:58,421 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,421 INFO  [stdout](default task-5)    at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:55)
00:00:58,422 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,422 INFO  [stdout](default task-5)    at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:64)
00:00:58,422 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,422 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:326)
00:00:58,422 INFO  [stdout](default task-5)    at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:448)
00:00:58,422 INFO  [stdout](default task-5)    at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:61)
00:00:58,422 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,423 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:326)
00:00:58,423 INFO  [stdout](default task-5)    at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80)
00:00:58,423 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,423 INFO  [stdout](default task-5)    at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
00:00:58,423 INFO  [stdout](default task-5)    at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:185)
00:00:58,423 INFO  [stdout](default task-5)    at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:182)
00:00:58,423 INFO  [stdout](default task-5)    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309)
00:00:58,424 INFO  [stdout](default task-5)    at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
00:00:58,424 INFO  [stdout](default task-5)    at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:73)
00:00:58,424 INFO  [stdout](default task-5)    at org.jboss.as.quickstarts.ear.ejb.GreeterEJB$$$view2.sayHello(Unknown Source)
00:00:58,424 INFO  [stdout](default task-5)    at org.jboss.as.quickstarts.ear.controller.Greeter.setName(Greeter.java:55)
00:00:58,424 INFO  [stdout](default task-5)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:00:58,424 INFO  [stdout](default task-5)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
00:00:58,424 INFO  [stdout](default task-5)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:58,424 INFO  [stdout](default task-5)    at java.lang.reflect.Method.invoke(Method.java:606)
00:00:58,425 INFO  [stdout](default task-5)    at javax.el.ELUtil.invokeMethod(ELUtil.java:308)
00:00:58,425 INFO  [stdout](default task-5)    at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
00:00:58,425 INFO  [stdout](default task-5)    at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
00:00:58,425 INFO  [stdout](default task-5)    at com.sun.el.parser.AstValue.invoke(AstValue.java:286)
00:00:58,425 INFO  [stdout](default task-5)    at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
00:00:58,425 INFO  [stdout](default task-5)    at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
00:00:58,425 INFO  [stdout](default task-5)    at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
00:00:58,425 INFO  [stdout](default task-5)    at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
00:00:58,426 INFO  [stdout](default task-5)    at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
00:00:58,426 INFO  [stdout](default task-5)    at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
00:00:58,426 INFO  [stdout](default task-5)    at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
00:00:58,426 INFO  [stdout](default task-5)    at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
00:00:58,426 INFO  [stdout](default task-5)    at javax.faces.component.UICommand.broadcast(UICommand.java:315)
00:00:58,427 INFO  [stdout](default task-5)    at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
00:00:58,427 INFO  [stdout](default task-5)    at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
00:00:58,427 INFO  [stdout](default task-5)    at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
00:00:58,427 INFO  [stdout](default task-5)    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
00:00:58,427 INFO  [stdout](default task-5)    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
00:00:58,428 INFO  [stdout](default task-5)    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
00:00:58,428 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
00:00:58,428 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
00:00:58,428 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
00:00:58,428 INFO  [stdout](default task-5)    at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
00:00:58,429 INFO  [stdout](default task-5)    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
00:00:58,429 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
00:00:58,429 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
00:00:58,429 INFO  [stdout](default task-5)    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
00:00:58,430 INFO  [stdout](default task-5)    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
00:00:58,430 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)
00:00:58,430 INFO  [stdout](default task-5)    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
00:00:58,430 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
00:00:58,431 INFO  [stdout](default task-5)    at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
00:00:58,431 INFO  [stdout](default task-5)    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
00:00:58,431 INFO  [stdout](default task-5)    at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
00:00:58,431 INFO  [stdout](default task-5)    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
00:00:58,432 INFO  [stdout](default task-5)    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
00:00:58,432 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
00:00:58,432 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)
00:00:58,432 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)
00:00:58,432 INFO  [stdout](default task-5)    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)
00:00:58,433 INFO  [stdout](default task-5)    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
00:00:58,433 INFO  [stdout](default task-5)    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
00:00:58,433 INFO  [stdout](default task-5)    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
00:00:58,433 INFO  [stdout](default task-5)    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
00:00:58,434 INFO  [stdout](default task-5)    at java.lang.Thread.run(Thread.java:745)

**Comment by RadekKoubsky** [comment]
Fixed, see to https://issues.jboss.org/browse/BYTEMAN-298
