### ISSUE TITLE
RULE logStatefulSessionSynchronizationInterceptor.processInvocation.popOwner verify error

### ISSUE THREAD

**Issue by RadekKoubsky** [RadekKoubsky/byteman-wildfly-log#2]
Throws verify error during transformation when ALL counter is used in AT INVOKE location specifier:
# Log StatefulSessionSynchronizationInterceptor - pop lock owner

RULE logStatefulSessionSynchronizationInterceptor.processInvocation.popOwner
CLASS org.jboss.as.ejb3.component.stateful.StatefulSessionSynchronizationInterceptor
METHOD processInvocation(InterceptorContext)
AT INVOKE org.jboss.as.ejb3.tx.OwnableReentrantLock.popOwner() ALL
IF true
DO log($CLASS, "DEBUG", "(Method processInvocation) Popping lock owner off the lock.")
ENDRULE

Stacktrace:

VerifyError during retransformation : some rules may not have been correctly injected or uninjected!
java.lang.VerifyError
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at org.jboss.byteman.agent.Retransformer.installScript(Retransformer.java:144)
at org.jboss.byteman.agent.TransformListener.handleScripts(TransformListener.java:349)
at org.jboss.byteman.agent.TransformListener.loadScripts(TransformListener.java:272)
at org.jboss.byteman.agent.TransformListener.handleConnection(TransformListener.java:225)
at org.jboss.byteman.agent.TransformListener.run(TransformListener.java:158)

**Comment by RadekKoubsky** [comment]
Resloved, see https://issues.jboss.org/browse/BYTEMAN-299
